#!/bin/bash
#$ -l mem_free=60G
#$ -l h_vmem=60G
#$ -l h_rt=24:00:00
#$ -cwd
#$ -j y
#$ -R y
#$ -t 1-1000

mkdir -p results
if [ ! -f "/results/run-$SGE_TASK_ID" ]; then
  Rscript analyzeParal.R $SGE_TASK_ID 1000 180 365 4000 30 15 100 1000
fi
