#!/bin/bash
#$ -l mem_free=20G
#$ -l h_vmem=20G
#$ -l h_rt=24:00:00
#$ -cwd
#$ -j y
#$ -R y
#$ -t 1-1000

mkdir -p truth
if [ ! -f "/truth/run-$SGE_TASK_ID" ]; then
  Rscript getTruthParal.R $SGE_TASK_ID 1000 30 15 180 1000
fi


